const products = [
  {
    _id: "1",
    name: "test1",
    image: "/_1bf77651-34cf-47e4-ab82-599ff8759c57.jpg",
    description: "testrtestrtestrtestrtestrtestrtestrtestrtestr",
    brand: "testr",
    category: "Homme",
    price: 50,
    countInStock: 30,
    rating: 3.5,
    numReviews: 12,
  },
  {
    _id: "2",
    name: "test2",
    image: "/_2521f6d0-ebce-4ced-8443-cc2ae705b203.jpg",
    description: "testrtestrtestrtestrtestrtestrtestrtestrtestr",
    brand: "testr",
    category: "Femme",
    price: 25,
    countInStock: 40,
    rating: 2.5,
    numReviews: 13,
  },
  {
    _id: "2",
    name: "test2",
    image: "/_2521f6d0-ebce-4ced-8443-cc2ae705b203.jpg",
    description: "testrtestrtestrtestrtestrtestrtestrtestrtestr",
    brand: "testr",
    category: "Femme",
    price: 25,
    countInStock: 40,
    rating: 2.5,
    numReviews: 13,
  },
  {
    _id: "2",
    name: "test2",
    image: "/_2521f6d0-ebce-4ced-8443-cc2ae705b203.jpg",
    description: "testrtestrtestrtestrtestrtestrtestrtestrtestr",
    brand: "testr",
    category: "Femme",
    price: 25,
    countInStock: 40,
    rating: 2.5,
    numReviews: 13,
  },
  {
    _id: "2",
    name: "test2",
    image: "/_2521f6d0-ebce-4ced-8443-cc2ae705b203.jpg",
    description: "testrtestrtestrtestrtestrtestrtestrtestrtestr",
    brand: "testr",
    category: "Femme",
    price: 25,
    countInStock: 40,
    rating: 2.5,
    numReviews: 13,
  },
  {
    _id: "2",
    name: "test2",
    image: "/_2521f6d0-ebce-4ced-8443-cc2ae705b203.jpg",
    description: "testrtestrtestrtestrtestrtestrtestrtestrtestr",
    brand: "testr",
    category: "Femme",
    price: 25,
    countInStock: 40,
    rating: 2.5,
    numReviews: 13,
  },
  {
    _id: "2",
    name: "test2",
    image: "/_2521f6d0-ebce-4ced-8443-cc2ae705b203.jpg",
    description: "testrtestrtestrtestrtestrtestrtestrtestrtestr",
    brand: "testr",
    category: "Femme",
    price: 25,
    countInStock: 40,
    rating: 2.5,
    numReviews: 13,
  },
  {
    _id: "2",
    name: "test2",
    image: "/_2521f6d0-ebce-4ced-8443-cc2ae705b203.jpg",
    description: "testrtestrtestrtestrtestrtestrtestrtestrtestr",
    brand: "testr",
    category: "Femme",
    price: 25,
    countInStock: 40,
    rating: 2.5,
    numReviews: 13,
  },
  {
    _id: "2",
    name: "test2",
    image: "/_2521f6d0-ebce-4ced-8443-cc2ae705b203.jpg",
    description: "testrtestrtestrtestrtestrtestrtestrtestrtestr",
    brand: "testr",
    category: "Femme",
    price: 25,
    countInStock: 40,
    rating: 2.5,
    numReviews: 13,
  },
  {
    _id: "2",
    name: "test2",
    image: "/_2521f6d0-ebce-4ced-8443-cc2ae705b203.jpg",
    description: "testrtestrtestrtestrtestrtestrtestrtestrtestr",
    brand: "testr",
    category: "Femme",
    price: 25,
    countInStock: 40,
    rating: 2.5,
    numReviews: 13,
  },
  {
    _id: "2",
    name: "test2",
    image: "/_2521f6d0-ebce-4ced-8443-cc2ae705b203.jpg",
    description: "testrtestrtestrtestrtestrtestrtestrtestrtestr",
    brand: "testr",
    category: "Femme",
    price: 25,
    countInStock: 40,
    rating: 2.5,
    numReviews: 13,
  },
  {
    _id: "2",
    name: "test2",
    image: "/_2521f6d0-ebce-4ced-8443-cc2ae705b203.jpg",
    description: "testrtestrtestrtestrtestrtestrtestrtestrtestr",
    brand: "testr",
    category: "Femme",
    price: 25,
    countInStock: 40,
    rating: 2.5,
    numReviews: 13,
  },
  {
    _id: "2",
    name: "test2",
    image: "/_2521f6d0-ebce-4ced-8443-cc2ae705b203.jpg",
    description: "testrtestrtestrtestrtestrtestrtestrtestrtestr",
    brand: "testr",
    category: "Femme",
    price: 25,
    countInStock: 40,
    rating: 2.5,
    numReviews: 13,
  },
  {
    _id: "2",
    name: "test2",
    image: "/_2521f6d0-ebce-4ced-8443-cc2ae705b203.jpg",
    description: "testrtestrtestrtestrtestrtestrtestrtestrtestr",
    brand: "testr",
    category: "Femme",
    price: 25,
    countInStock: 40,
    rating: 2.5,
    numReviews: 13,
  },
];

export default products;
